Fix detox logs not being archived
Since we immediately fail on any shell errors we miss log
collection at the end of the build. Fix detox part of script to
allow the log collection code to run.

Change-Id: I50bcd337224adcecbf028f08b56cfebe2e10a3d4
Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

diff --git a/.jjb-test/expected-xml/github-python-tox-verify-master b/.jjb-test/expected-xml/github-python-tox-verify-master
--- a/.jjb-test/expected-xml/github-python-tox-verify-master
+++ b/.jjb-test/expected-xml/github-python-tox-verify-master
@@ -296,10 +296,13 @@ if [ -d &quot;/opt/pyenv&quot; ]; then
     export PATH=&quot;$PYENV_ROOT/bin:$PATH&quot;
 fi
 
+set +e  # Allow detox to fail so that we can collect the logs in the next step
 if [ ! -z &quot;$TOX_ENVS&quot; ]; then
     detox -e &quot;$TOX_ENVS&quot;  | tee -a &quot;$ARCHIVE_TOX_DIR/detox.log&quot;
+    detox_status=&quot;${PIPESTATUS[0]}&quot;
 else
     detox | tee -a &quot;$ARCHIVE_TOX_DIR/detox.log&quot;
+    detox_status=&quot;${PIPESTATUS[0]}&quot;
 fi
 
 # Disable SC2116 as we want to echo a space separated list of TOX_ENVS
@@ -307,8 +310,11 @@ fi
 for i in $(echo &quot;${TOX_ENVS//,/ }&quot;); do
     cp -r &quot;.tox/$i/log&quot; &quot;$ARCHIVE_TOX_DIR/$i&quot;
 done
+set -e  # Logs collected so re-enable
 
 echo &quot;Completed tox runs.&quot;
+
+test &quot;$detox_status&quot; -eq 0 || exit &quot;$detox_status&quot;
 </command>
     </hudson.tasks.Shell>
   </builders>
